version: '3'

services:
  # fastapi:
  #   build: .
  #   command: python ./src/main.py
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #     - DB_NAME=${DB_NAME}
  #     # - DB_HOST=${DB_HOST}
  #     - DB_HOST=database
  #     - DB_PORT=${DB_PORT}
  #   depends_on:
  #     - database
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA= /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@mail.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASS}